FROM node:24-alpine

WORKDIR /app

ENV NODE_ENV=development

COPY package.json package-lock.json* ./
RUN npm install

COPY tsconfig*.json vite.config.ts postcss.config.cjs ./
COPY index.html ./

COPY src ./src
COPY public ./public

RUN chown -R node:node /app

EXPOSE 5173

USER node

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
