services:
  # Backend Server (Express API)
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: hypertube-server
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=production
    ports:
      - '3000:3000'
    volumes:
      - server_downloads:/app/downloads
      - server_uploads:/app/uploads
      - subs:/app/public/subtitles
    networks:
      - hypertube-network

  # Frontend Client (React + Vite)
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: hypertube-client
    depends_on:
      - server
    env_file:
      - ./client/.env
    ports:
      - '5173:5173'
    networks:
      - hypertube-network

volumes:
  server_downloads:
  server_uploads:
  subs:

networks:
  hypertube-network:
    driver: bridge
