name: Backend CI
on:
  push:
    branches: [ main ]
    paths:
      - 'server/**'
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: server/package-lock.json
      - run: npm ci
      - run: npm run lint
      - run: npm test -- --passWithNoTests
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      NODE_ENV: "test"
      SESSION_SECRET: "super_secret_dummy_value_for_ci"
      TMDB_API_KEY: "dummy_tmdb_key"
      TMDB_API_ACCESS_TOKEN: "dummy_tmdb_token"
